export type CompanyReport = {
    company_id: number,
    company_name: string,
    registrations: number,
    orders: number,
    schedules: number,
    attendance: number,
    attendance_attended: number,
    active_schedules: number,
    incomes: number,
    online_income: number,
    transactions: number,
    online_transactions: number,
    emails_sent: number,
    widgets_visits: number,
    events: number,
    date: string
    active: number,
    registered: number,
    inactive: number,
    waitlist: number,
    late: number,
}
